// Generated by CoffeeScript 1.6.3
(function() {
  var confurg, cson, fs, merge, path, root;

  fs = require('fs');

  path = require('path');

  cson = require('cson');

  merge = require('tea-merge');

  root = require('root-finder');

  confurg = module.exports = {
    init: function(config, defaults) {
      var f, key, matched, merged, re, val, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4;
      if (config == null) {
        config = {};
      }
      if (defaults == null) {
        defaults = {};
      }
      if (typeof config === "string") {
        config = {
          namespace: config
        };
      }
      if (!((_ref = config.namespace) != null ? _ref.match(/^[\w\-\.]+$/) : void 0)) {
        throw "Need namespace config parameter";
      }
      if (config.cwd == null) {
        config.cwd = path.dirname(module.parent.filename);
      }
      console.log("path is", config.cwd);
      if (config.defaults == null) {
        config.defaults = defaults;
      }
      if (config.config == null) {
        config.config = path.join(config.cwd, "config");
      }
      if (config.home == null) {
        config.home = path.join(process.env.HOME, "." + config.namespace);
      }
      if (config.cli == null) {
        config.cli = require("yargs").argv;
      }
      if (!config.env) {
        re = new RegExp("^" + config.namespace + "_(\\w+)");
        config.env = {};
        _ref1 = process.env;
        for (key in _ref1) {
          val = _ref1[key];
          if (matched = (_ref2 = key.match(re)) != null ? _ref2[1] : void 0) {
            config.env[matched] = val;
          }
        }
      }
      merged = {};
      _ref3 = ['defaults', 'config', 'home', 'env', 'cli'];
      for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
        key = _ref3[_i];
        val = config[key];
        switch (typeof val) {
          case 'string':
            _ref4 = val.match(/\.[jc]son$/) && [val] || ["" + val + ".cson", "" + val + ".json"];
            for (_j = 0, _len1 = _ref4.length; _j < _len1; _j++) {
              f = _ref4[_j];
              if (fs.existsSync(f)) {
                merge(merged, cson.parseFileSync(f));
                break;
              }
            }
            break;
          case 'object':
            merge(merged, val);
            break;
          default:
            throw "Don't know what to do with content in " + key + " (" + (typeof val) + ")";
        }
      }
      return merged;
    }
  };

}).call(this);
